(function(g){var window=this;var xla=function(a,b){return g.jc(a,b)},h4=function(){},yla=function(a){if(a.wc&&"function"==typeof a.wc)return a.wc();
if(g.v(a))return a.split("");if(g.Ea(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.fc(a)},zla=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ea(a)||g.v(a))(0,g.C)(a,b,void 0);else{if(a.Bd&&"function"==typeof a.Bd)var c=a.Bd();else if(a.wc&&"function"==typeof a.wc)c=void 0;else if(g.Ea(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.gc(a);d=yla(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},i4=function(a){g.Ro(a,"zx",g.Pb());
return a},j4=function(a,b,c){g.Da(c)||(c=[String(c)]);
g.Wo(a.o,b,c)},k4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},l4=function(a){var b;
(b=a.g)||(b={},k4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},m4=function(a){return(a=k4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},n4=function(a,b){return b+" ["+a.Y+" "+a.H+" "+a.getStatus()+"]"},Ala=function(a){return"content-type"==a.toLowerCase()},o4=function(a){a.g&&a.N&&(a.g.ontimeout=null);
a.F&&(g.w.clearTimeout(a.F),a.F=null)},Bla=function(a){return g.Wd&&g.Gc(9)&&g.wa(a.timeout)&&g.t(a.ontimeout)},p4=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},q4=function(a,b){if(a.g){o4(a);
var c=a.g,d=a.R[0]?g.Aa:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},r4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;p4(a);q4(a)},s4=function(a){return a.g?a.g.readyState:0},t4=function(a){if(a.l&&"undefined"!=typeof g.qW)if(a.R[1]&&4==s4(a)&&2==a.getStatus())n4(a,"Local request error detected and ignored");
else if(a.G&&4==s4(a))g.Ig(a.Tu,0,a);else if(a.dispatchEvent("readystatechange"),4==s4(a)){n4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.$g(String(a.H))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Cla.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<s4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";p4(a)}}finally{q4(a)}}},u4=function(a){g.Qf.call(this);
this.headers=new g.Go;this.T=a||null;this.l=!1;this.R=this.g=null;this.Y=this.H="";this.A=0;this.B="";this.o=this.Z=this.G=this.U=!1;this.C=0;this.F=null;this.ga="";this.N=this.ba=!1},v4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Dla=function(a,b){var c=[];
g.El(b,function(a){try{var b=g.tq.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.sq(b)&&c.push(a):c.push(a)},a);
return c},Ela=function(a,b){var c=Dla(a,b);
(0,g.C)(c,function(a){g.tq.prototype.remove.call(this,a)},a)},w4=function(a){if(a.Vc){if(a.Vc.locationOverrideToken)return{locationOverrideToken:a.Vc.locationOverrideToken};
if(null!=a.Vc.latitudeE7&&null!=a.Vc.longitudeE7)return{latitudeE7:a.Vc.latitudeE7,longitudeE7:a.Vc.longitudeE7}}return null},Fla=function(a,b,c,d){var e=new g.Jo(null,void 0);
a&&g.Ko(e,a);b&&g.Lo(e,b);c&&g.Mo(e,c);d&&(e.l=d);return e},x4=function(){this.g=[];
this.l=[]},y4=function(a){g.bt[a]&&(a=g.bt[a],(0,g.C)(a,function(a){g.$s[a]&&delete g.$s[a]}),a.length=0)},Gla=function(a){var b=g.Zs();
if(b)if(b.clear(a),a)y4(a);else for(var c in g.bt)y4(c)},z4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Go;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Hla(this,a.capabilities||""),Ila(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Hla=function(a,b){a.capabilities.clear();
(0,g.ke)(b.split(","),g.Ma(xla,Jla)).forEach(function(b){a.capabilities.add(b)})},Ila=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},A4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},B4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},C4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Kla=function(a){return new A4(a)},D4=function(a){return g.Da(a)?(0,g.E)(a,Kla):[]},E4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},F4=function(a){return g.Da(a)?"["+(0,g.E)(a,E4).join(",")+"]":"null"},G4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Lla=function(a){return(0,g.E)(a,function(a){return{key:a.id,
name:a.name}})},H4=function(a,b){return g.Sa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},I4=function(a,b){return g.Sa(a,function(a){return B4(a,b)})},Mla=function(){var a=(0,g.au)();
a&&Ela(a,a.g.gf(!0))},J4=function(){var a=g.du("yt-remote-connected-devices")||[];
g.pb(a);return a},Nla=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.E)(a,function(a,b){return 0==b?a:a.substring(c.length)})},K4=function(a){g.cu("yt-remote-connected-devices",a,86400)},M4=function(){if(L4)return L4;
var a=g.du("yt-remote-device-id");a||(a=G4(),g.cu("yt-remote-device-id",a,31536E3));for(var b=J4(),c=1,d=a;g.Wa(b,d);)c++,d=a+"#"+c;return L4=d},N4=function(){var a=J4(),b=M4();
g.Wa(a,b);g.fu()&&g.tb(a,b);a=Nla(a);if(0==a.length)try{g.Lt("remote_sid")}catch(c){}else try{g.Kt("remote_sid",a.join(","),-1)}catch(c){}},O4=function(){return g.du("yt-remote-session-browser-channel")},P4=function(){return g.du("yt-remote-local-screens")||[]},Q4=function(){g.cu("yt-remote-lounge-token-expiration",!0,86400)},Ola=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.E)(P4(),function(a){return a.loungeToken}),c=(0,g.E)(a,function(a){return a.loungeToken});
(0,g.to)(c,function(a){return!g.Wa(b,a)})&&Q4();
g.cu("yt-remote-local-screens",a,31536E3)},Pla=function(a,b){g.cu("yt-remote-session-browser-channel",a);
g.cu("yt-remote-session-screen-id",b);var c=J4(),d=M4();g.Wa(c,d)||c.push(d);K4(c);N4()},R4=function(a){a||(g.eu("yt-remote-session-screen-id"),g.eu("yt-remote-session-video-id"));
N4();a=J4();g.ab(a,M4());K4(a)},T4=function(){if(!S4){var a=g.Dq();
a&&(S4=new g.nq(a))}return S4?!!S4.get("yt-remote-use-staging-server"):!1},Qla=function(){var a=window.document.createElement("a");
g.wd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Tb(a)},Rla=function(a,b){var c=g.de("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.xd(c,g.Ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Sla=function(){var a=Qla(),b=window.document.getElementById(a),c=b&&g.ms(b,"loaded");
c||b&&!c||(b=Rla(a,function(){g.ms(b,"loaded")||(g.ls(b,"loaded","true"),g.ft(a),g.jr(g.Ma(Gla,a),0))}))},U4=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},V4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},X4=function(a){a.length?W4(a.shift(),function(){X4(a)}):Y4()},Tla=function(a){return"chrome-extension://"+a+Z4},W4=function(a,b,
c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},$4=function(a){return 0<=window.navigator.userAgent.indexOf(a)},Y4=function(){var a=V4();
a&&a(!1,"No cast extension found")},a5=function(){if(Ula){var a=2,b=V4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;W4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Y4,c)}},Vla=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(a5(),a({command:"cast.sender.init"}))},Wla=function(){a5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);X4(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+Z4,"//www.gstatic.com/eureka/clank"+Z4])},b5=function(a,b,c){g.F.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.Rc=b;this.B=(0,g.A)(this.GC,this);this.g=!1;this.l=0;this.o=this.Ca=null;this.A=[]},c5=function(){},d5=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.C=d||1;this.A=45E3;this.ca=new g.Xo(this);this.l=new g.Hg;this.l.setInterval(250)},f5=function(a,b,c){a.ni=1;
a.sg=i4(b.clone());a.Eh=c;a.B=!0;e5(a,null)},g5=function(a,b,c,d,e){a.ni=1;
a.sg=i4(b.clone());a.Eh=null;a.B=c;e&&(a.wz=!1);e5(a,d)},e5=function(a,b){a.Ri=(0,g.D)();
h5(a);a.Jg=a.sg.clone();j4(a.Jg,"t",a.C);a.Uk=0;a.sc=a.g.Wo(a.g.Lk()?b:null);0<a.Ep&&(a.un=new g.Cm((0,g.A)(a.CA,a,a.sc),a.Ep));a.ca.ea(a.sc,"readystatechange",a.PL);var c=a.jh?g.rc(a.jh):{};a.Eh?(a.bo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Jg,a.bo,a.Eh,c)):(a.bo="GET",a.wz&&!g.Yd&&(c.Connection="close"),a.sc.send(a.Jg,a.bo,null,c));a.g.xe(1)},o5=function(a,b,c){for(var d=!0;!a.Yg&&a.Uk<c.length;){var e=Xla(a,c);
if(e==i5){4==b&&(a.tg=4,j5(15),d=!1);break}else if(e==k5){a.tg=4;j5(16);d=!1;break}else l5(a,e)}4==b&&0==c.length&&(a.tg=1,j5(17),d=!1);a.Be=a.Be&&d;d||(m5(a),n5(a))},Xla=function(a,b){var c=a.Uk,d=b.indexOf("\n",c);
if(-1==d)return i5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return k5;d+=1;if(d+c>b.length)return i5;var e=b.substr(d,c);a.Uk=d+c;return e},r5=function(a,b){a.Ri=(0,g.D)();
h5(a);var c=b?window.location.hostname:"";a.Jg=a.sg.clone();g.Ro(a.Jg,"DOMAIN",c);g.Ro(a.Jg,"t",a.C);try{a.Ce=new window.ActiveXObject("htmlfile")}catch(n){m5(a);a.tg=7;j5(22);n5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in p5)k=p5[l];else if(l in q5)k=p5[l]=q5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
p5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.yd(g.Rc("b/12014412"),d+"</body></html>");a.Ce.open();a.Ce.write(g.qd(c));a.Ce.close();a.Ce.parentWindow.m=(0,g.A)(a.jL,a);a.Ce.parentWindow.d=(0,g.A)(a.Fy,a,!0);a.Ce.parentWindow.rpcClose=(0,g.A)(a.Fy,a,!1);c=a.Ce.createElement("DIV");a.Ce.parentWindow.document.body.appendChild(c);d=g.bd(a.Jg.toString());d=g.Jb(g.Zc(d));d=g.yd(g.Rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.vd(c,g.qd(d));a.g.xe(1)},h5=function(a){a.Es=(0,g.D)()+
a.A;
s5(a,a.A)},s5=function(a,b){if(null!=a.dj)throw Error("WatchDog timer not null");
a.dj=t5((0,g.A)(a.uL,a),b)},u5=function(a){a.dj&&(g.w.clearTimeout(a.dj),a.dj=null)},n5=function(a){a.g.Ru()||a.Yg||a.g.bn(a)},m5=function(a){u5(a);
g.lf(a.un);a.un=null;a.l.stop();g.Zo(a.ca);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.Ce&&(a.Ce=null)},l5=function(a,b){try{a.g.yy(a,b),a.g.xe(4)}catch(c){}},w5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;v5(a,b,function(e){e?c(!0):g.w.setTimeout(function(){w5(a,b,c,d,f)},f)})}},v5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{x5(d),c(!0)}catch(e){}};
d.onerror=function(){try{x5(d),c(!1)}catch(e){}};
d.onabort=function(){try{x5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{x5(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},x5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},y5=function(a){this.g=a;
this.l=new c5},A5=function(a){var b=z5(a.g,a.nj,"/mail/images/cleardot.gif");
i4(b);w5(b.toString(),5E3,(0,g.A)(a.cC,a),3,2E3);a.xe(1)},C5=function(a){var b=a.g.H;
if(null!=b)j5(5),b?(j5(11),B5(a.g,a,!1)):(j5(12),B5(a.g,a,!0));else if(a.Kd=new d5(a,void 0,void 0,void 0),a.Kd.jh=a.Cp,b=a.g,b=z5(b,b.Lk()?a.Sj:null,a.Dp),j5(5),!g.Wd||g.Ic(10))j4(b,"TYPE","xmlhttp"),g5(a.Kd,b,!1,a.Sj,!1);else{j4(b,"TYPE","html");var c=a.Kd;a=!!a.Sj;c.ni=3;c.sg=i4(b.clone());r5(c,a)}},D5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new c5;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},Yla=function(a,b){this.g=a;
this.map=b;this.context=null},E5=function(a){g.nf.call(this,"statevent",a)},F5=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},G5=function(a){g.nf.call(this,"serverreachability",a)},K5=function(a){H5(a);
if(3==a.g){var b=a.wk++,c=a.Tl.clone();g.Ro(c,"SID",a.o);g.Ro(c,"RID",b);g.Ro(c,"TYPE","terminate");I5(a,c);b=new d5(a,a.o,b,void 0);b.ni=2;b.sg=i4(c.clone());(new window.Image).src=b.sg;b.Ri=(0,g.D)();h5(b)}J5(a)},M5=function(a){a.qC(1,0);
a.Tl=z5(a,null,a.Bp);L5(a)},H5=function(a){a.hg&&(a.hg.abort(),a.hg=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.kf&&(g.w.clearTimeout(a.kf),a.kf=null);N5(a);a.td&&(a.td.cancel(),a.td=null);a.ng&&(g.w.clearTimeout(a.ng),a.ng=null)},O5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new Yla(a.wH++,b));2!=a.g&&3!=a.g||L5(a)},L5=function(a){a.td||a.ng||(a.ng=t5((0,g.A)(a.Dy,a),0),a.hi=0)},R5=function(a,b){if(1==a.g){if(!b){a.wk=Math.floor(1E5*Math.random());
var c=a.wk++,d=new d5(a,"",c,void 0);d.jh=null;var e=P5(a),f=a.Tl.clone();g.Ro(f,"RID",c);g.Ro(f,"CVER","1");I5(a,f);f5(d,f,e);a.td=d;a.g=2}}else 3==a.g&&(b?Q5(a,b):0==a.l.length||a.td||Q5(a))},Q5=function(a,b){if(b)if(6<a.Zg){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.wk-1;var d=P5(a)}else c=b.F,d=b.Eh;else c=a.wk++,d=P5(a);var e=a.Tl.clone();g.Ro(e,"SID",a.o);g.Ro(e,"RID",c);g.Ro(e,"AID",a.wi);I5(a,e);c=new d5(a,a.o,c,a.hi+1);c.jh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.td=c;f5(c,e,d)},I5=function(a,b){if(a.Qc){var c=a.Qc.Bu();
c&&g.$b(c,function(a,c){g.Ro(b,c,a)})}},P5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Zg&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Zg?e:f-d;try{g.$b(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},S5=function(a){a.Rb||a.kf||(a.F=1,a.kf=t5((0,g.A)(a.Cy,a),0),a.Yh=0)},U5=function(a){if(a.Rb||a.kf||3<=a.Yh)return!1;
a.F++;a.kf=t5((0,g.A)(a.Cy,a),T5(a,a.Yh));a.Yh++;return!0},B5=function(a,b,c){a.Zn=c;
a.Pe=b.wf;a.C||M5(a)},N5=function(a){null!=a.bh&&(g.w.clearTimeout(a.bh),a.bh=null)},T5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W5=function(a,b){if(2==b||9==b){var c=null;
a.Qc&&(c=null);var d=(0,g.A)(a.sM,a);c||(c=new g.Jo("//www.google.com/images/cleardot.gif"),i4(c));v5(c.toString(),1E4,d)}else j5(2);V5(a,b)},V5=function(a,b){a.g=0;
a.Qc&&a.Qc.Nt(b);J5(a);H5(a)},J5=function(a){a.g=0;
a.Pe=-1;if(a.Qc)if(0==a.A.length&&0==a.l.length)a.Qc.Lo();else{g.eb(a.A);var b=g.eb(a.l);a.A.length=0;a.l.length=0;a.Qc.Lo(b)}},z5=function(a,b,c){var d=g.So(c);
if(""!=d.g)b&&g.Lo(d,b+"."+d.g),g.Mo(d,d.B);else{var e=window.location;d=Fla(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Aj&&g.$b(a.Aj,function(a,b){g.Ro(d,b,a)});
g.Ro(d,"VER",a.Zg);I5(a,d);return d},t5=function(a,b){if(!g.Fa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},j5=function(a){X5.dispatchEvent(new E5(X5,a))},Y5=function(){},Zla=function(a,b){this.action=a;
this.params=b||{}},Z5=function(a,b){g.F.call(this);
this.g=new g.L(this.cL,0,this);g.I(this,this.g);this.Rc=5E3;this.l=0;if(g.Fa(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Fa(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},$5=function(a,b,c){this.N=a;
this.C=b;this.o=new g.mq;this.l=new Z5(this.VM,this);this.g=null;this.J=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.R=c||!1},$la=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Zn,sessionId:a.g.o,arrayId:a.g.wi}},a6=function(a,b){a.G=b||0;
a.l.stop();a.g&&(3==a.g.g&&R5(a.g),K5(a.g));a.G=0},b6=function(a){return!!a.g&&3==a.g.g},ama=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},c6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.ch(a)||"";b&&(this.port=":"+b);this.domain=g.bh(a)||"";a=g.Yb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sb(a,"10.0")&&(this.l=!1))},d6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.lh(c+b,{})},e6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ma(a.A,d,!0),onError:g.Ma(a.o,e),hd:g.Ma(a.B,e)};c&&(a.ib=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Br(b,a)},bma=function(){var a=f6;
g6();h6.push(a);i6(h6)},j6=function(a,b){g6();
var c=h6,d=cma(a,String(b));0==c.length?dma(d):(i6(c),(0,g.C)(c,function(a){a(d)}))},g6=function(){h6||(h6=g.z("yt.mdx.remote.debug.handlers_")||[],g.y("yt.mdx.remote.debug.handlers_",h6,void 0))},dma=function(a){var b=(k6+1)%50;
k6=b;l6[b]=a;m6||(m6=49==b)},i6=function(a){var b=l6;
if(b[0]){var c=k6,d=m6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
l6=Array(50);k6=-1;m6=!1}},cma=function(a,b){var c=((0,g.D)()-ema)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n6=function(a){g.O.call(this);
this.F=a;this.g=[]},o6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},fma=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.ke)(a.g,function(a){return!!H4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=o6(a,b[d])||c;return c},gma=function(a,b){var c=a.g.length;
a.g=(0,g.ke)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},p6=function(a,b,c,d){g.O.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ca=window.NaN},r6=function(a){n6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;q6(this);this.info("Initializing with "+F4(this.g))},s6=function(a){if(a.g.length){var b=(0,g.E)(a.g,function(a){return a.id}),c=d6(a.o,"/pairing/get_lounge_token_batch");
e6(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.RC,a),(0,g.A)(a.QC,a))}},q6=function(a){var b=D4(P4());
b=(0,g.ke)(b,function(a){return!a.uuid});
return fma(a,b)},t6=function(a,b){Ola((0,g.E)(a.g,C4));
b&&Q4()},v6=function(a,b){g.O.call(this);
this.C=b;var c=g.du("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Wa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;u6("Initialized with "+g.Sg(this.g))},w6=function(a,b,c){var d=d6(a.B,"/pairing/get_screen_availability");
e6(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},x6=function(a,b){a:if(g.dc(b)!=g.dc(a.g))var c=!1;
else{c=g.gc(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(u6("Updated online screens: "+g.Sg(a.g)),a.g=b,a.P("screenChange"));hma(a)},y6=function(a){(0,window.isNaN)(a.o)||g.lr(a.o);
a.o=g.jr((0,g.A)(a.Pr,a),0<a.A&&a.A<(0,g.D)()?2E4:1E4)},u6=function(a){j6("OnlineScreenService",a)},z6=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.Eb("Requesting availability of screen w/o lounge token.")});
return b},hma=function(a){a=g.gc(g.ac(a.g,function(a){return a}));
g.pb(a);a.length?g.cu("yt-remote-online-screen-ids",a.join(","),60):g.eu("yt-remote-online-screen-ids")},A6=function(a){n6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};jma(this)},C6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Dd();if(k=(c?I4(k,c):null)||I4(k,b)){k.uuid=b;var l=B6(a,k);w6(a.l,l,function(a){e(a?l:null)})}else c?kma(a,c,(0,g.A)(function(a){var f=B6(this,new A4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));w6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},D6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},kma=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ib:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Br(d6(a.C,"/pairing/get_lounge_token_batch"),e)},E6=function(a){a.g=a.o.Dd();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+F4(a.g))},jma=function(a){F6(a);
a.o=new r6(a.C);a.o.subscribe("screenChange",(0,g.A)(a.cD,a));E6(a);a.A=D4(g.du("yt-remote-automatic-screen-cache")||[]);F6(a);a.info("Initializing automatic screens: "+F4(a.A));a.l=new v6(a.C,(0,g.A)(a.Dd,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.P("onlineScreenChange")},a))},B6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=I4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.cu("yt-remote-automatic-screen-cache",(0,g.E)(a.A,C4)));F6(a);a.B[b.uuid]=b.id;g.cu("yt-remote-device-id-map",a.B,31536E3);return b},F6=function(a){a.B=g.du("yt-remote-device-id-map")||{}},G6=function(a,b,c){g.O.call(this);
this.R=c;this.H=a;this.l=b;this.o=null},H6=function(a,b){j6(a.R,b)},J6=function(a,b){G6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.bN,this);this.B=(0,g.A)(this.FL,this);this.A=g.jr((0,g.A)(function(){I6(this,null)},this),12E4)},lma=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Sg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Aa,(0,g.A)(function(){H6(this,"Failed to send message: getMdxSessionStatus.")},a)):H6(a,"Sending yt message without session: "+g.Sg(b))},I6=function(a,b){g.lr(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.cn,a),d=(0,g.A)(a.Id,a);a.Ju(b,c,d,5)}}else a.Id(Error("Waiting for session status timed out."))},K6=function(a,b,c){G6.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.T=c;this.B=null;this.F=g.Aa;this.C=window.NaN;this.N=(0,g.A)(this.eN,this);this.g=g.Aa},L6=function(a){a.g=a.H.IA(a.J,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.Aa;
this.cn(a)},a),(0,g.A)(function(a){this.g=g.Aa;
this.Id(a)},a))},M6=function(a){var b={};
b.pairingCode=a.J;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}T4()&&(b.env_useStageMdx=1);return g.jh(b)},N6=function(a,b){G6.call(this,a,b,"ManualSession");
this.g=g.jr((0,g.A)(this.xi,this,null),150)},O6=function(a,b,c,d){g.O.call(this);
this.l=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.pK,this)},P6=function(a,b){return b?g.Sa(a.o,function(a){return B4(b,a.label)},a):null},Q6=function(a){j6("Controller",a)},f6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},R6=function(a){return a.B||!!a.o.length||!!a.g},S6=function(a,b,c){b!=a.g&&(g.lf(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.By,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.xi(null)):a.P("yt-remote-cast2-session-change",null))},T6=function(a){var b=a.l.HA(),c=a.g&&a.g.l;
a=(0,g.E)(b,function(a){c&&B4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=P6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},pma=function(a,b,c,d,e,f,k){mma()?nma(b,e,f,k)&&(V6(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?W6(a,c):(window.__onGCastApiAvailable=function(b,d){b?W6(a,c):(X6("Failed to load cast API: "+d),Y6(!1),V6(!1),g.eu("yt-remote-cast-available"),g.eu("yt-remote-cast-receiver"),Z6(),c(!1))},
d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Sla():$4("CriOS")?Vla():$4("Android")&&$4("Chrome/")&&window.navigator.presentation?Wla():window.chrome&&window.navigator.presentation&&!$4("Edge")?(a5(),X4(oma.map(Tla))):Y4())):U6("Cannot initialize because not running Chrome")},Z6=function(){U6("dispose");
var a=$6();a&&a.dispose();g.y("yt.mdx.remote.cloudview.instance_",null,void 0);a7(!1);g.dt(b7);b7.length=0},c7=function(){return!!g.du("yt-remote-cast-installed")},d7=function(){var a=g.du("yt-remote-cast-receiver");
return a?a.friendlyName:null},e7=function(){U6("clearCurrentReceiver");
g.eu("yt-remote-cast-receiver")},f7=function(){return c7()?$6()?$6().getCastSession():(X6("getCastSelector: Cast is not initialized."),null):(X6("getCastSelector: Cast API is not installed!"),null)},h7=function(){c7()?$6()?g7()?(U6("Requesting cast selector."),$6().requestSession()):(U6("Wait for cast API to be ready to request the session."),b7.push(g.ct("yt-remote-cast2-api-ready",h7))):X6("requestCastSelector: Cast is not initialized."):X6("requestCastSelector: Cast API is not installed!")},i7=
function(a,b){g7()?$6().setConnectedScreenStatus(a,b):X6("setConnectedScreenStatus called before ready.")},mma=function(){var a=0<=g.Yb.search(/ (CrMo|Chrome|CriOS)\//);
return g.vv||a},qma=function(a,b){$6().init(a,b)},nma=function(a,b,c,d){var e=!1;
$6()||(a=new O6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.cu("yt-remote-cast-available",a);g.gt("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){U6("onReceiverSelected: "+a.friendlyName);
g.cu("yt-remote-cast-receiver",a);g.gt("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){U6("onReceiverResumed: "+a.friendlyName);
g.cu("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){U6("onSessionChange: "+E4(a));
a||g.eu("yt-remote-cast-receiver");g.gt("yt-remote-cast2-session-change",a)}),g.y("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
U6("cloudview.createSingleton_: "+e);return e},$6=function(){return g.z("yt.mdx.remote.cloudview.instance_")},W6=function(a,b){Y6(!0);
V6(!1);qma(a,function(a){a?(a7(!0),g.ft("yt-remote-cast2-api-ready")):(X6("Failed to initialize cast API."),Y6(!1),g.eu("yt-remote-cast-available"),g.eu("yt-remote-cast-receiver"),Z6());b(a)})},U6=function(a){j6("cloudview",a)},X6=function(a){j6("cloudview",a)},Y6=function(a){U6("setCastInstalled_ "+a);
g.cu("yt-remote-cast-installed",a)},g7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},a7=function(a){U6("setApiReady_ "+a);
g.y("yt.mdx.remote.cloudview.apiReady_",a,void 0)},V6=function(a){g.y("yt.mdx.remote.cloudview.initializing_",a,void 0)},j7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.l=null;this.hasNext=this.Se=!1;this.J=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},k7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Se=!1;a.hasNext=!1;a.G=0;a.F=(0,g.D)();a.B=0;a.o=0;a.H=0;a.J=0;a.A=window.NaN;a.C=!1},l7=function(a){return 1==a.g?((0,g.D)()-a.F)/1E3:0},m7=function(a,b){a.G=b;
a.F=(0,g.D)()},n7=function(a){switch(a.g){case 1:case 1081:return((0,g.D)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},o7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&k7(a)},p7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.sc(a.l);b.hasPrevious=a.Se;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.A;return b},s7=function(a,b){g.O.call(this);
this.g=0;this.A=a;this.C=[];this.B=new x4;this.o=this.l=null;this.H=(0,g.A)(this.fI,this);this.F=(0,g.A)(this.yk,this);this.G=(0,g.A)(this.eI,this);this.J=(0,g.A)(this.rI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Gs,this),q7(this))):c=3;0!=c&&(b?this.Gs(c):g.jr((0,g.A)(function(){this.Gs(c)},this),0));
var d=f7();d&&r7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},t7=function(a){return new j7(a.A.getPlayerContextData())},q7=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ma(this.lK,a),this))},a)},u7=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},v7=function(a,b){var c=a.B;
50>c.g.length+c.l.length&&a.B.l.push(b)},x7=function(a,b,c){var d=t7(a);
m7(d,c);-1E3!=d.g&&(d.g=b);w7(a,d)},y7=function(a,b,c){a.A.sendMessage(b,c)},w7=function(a,b){u7(a);
a.A.setPlayerContextData(p7(b));q7(a)},r7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.F),a.yk(null));
a.o=b;a.o&&(j6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.F),a.o.media.length&&a.yk(a.o.media[0]))},z7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=t7(a);b.contentId!=d.videoId&&j6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;m7(d,a.l.getEstimatedTime());w7(a,d)}else j6("CP","No cast media video. Ignoring state update.")},A7=function(a,b,c){return(0,g.A)(function(a){this.Eb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Eb("Retrying "+b+" using MDx browser channel."),y7(this,b,c))},a)},B7=function(a,b,c){g.O.call(this);
this.B=window.NaN;this.T=!1;this.J=this.H=this.N=this.R=window.NaN;this.U=[];this.A=this.F=this.o=this.Na=this.g=null;this.ra=a;this.U.push(g.Cs(window,"beforeunload",(0,g.A)(this.KC,this)));this.l=[];this.Na=new j7;this.Z=b.id;this.g=rma(this,c);this.g.subscribe("handlerOpened",this.jI,this);this.g.subscribe("handlerClosed",this.gI,this);this.g.subscribe("handlerError",this.hI,this);this.g.subscribe("handlerMessage",this.iI,this);ama(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Na.videoId;g.fu()&&g.cu("yt-remote-session-video-id",a)},this)},C7=function(a){j6("conn",a)},rma=function(a,b){return new $5(d6(a.ra,"/bc"),b)},D7=function(a,b){a.P("proxyStateChange",b)},sma=function(a){a.B=g.jr((0,g.A)(function(){C7("Connecting timeout");
this.C(1)},a),2E4)},E7=function(a){g.lr(a.B);
a.B=window.NaN},F7=function(a){g.lr(a.R);
a.R=window.NaN},tma=function(a){G7(a);
a.N=g.jr((0,g.A)(function(){H7(this,"getNowPlaying")},a),2E4)},G7=function(a){g.lr(a.N);
a.N=window.NaN},J7=function(a,b){b&&(E7(a),F7(a));
b==(b6(a.g)&&(0,window.isNaN)(a.B))?b&&(D7(a,1),H7(a,"getSubtitlesTrack")):b?(a.ba()&&a.Na.reset(),D7(a,1),H7(a,"getNowPlaying"),I7(a)):a.C(1)},uma=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Na.videoId&&(g.mc(b.params)?a.Na.l=null:a.Na.l=b.params,a.P("remotePlayerChange"))},K7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Na.listId=b.params.listId||a.Na.listId;o7(a.Na,c,d);a.P("remoteQueueChange")},vma=function(a,b){b.params=b.params||{};
K7(a,b);L7(a,b);a.P("autoplayDismissed")},L7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
m7(a.Na,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Na.g&&(c=-1E3);a.Na.g=c;c=Number(b.params.loadedTime);a.Na.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Na.H=(0,window.isNaN)(c)?0:c;c=a.Na;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Na;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Na.g?tma(a):G7(a);
a.P("remotePlayerChange")},wma=function(a,b){if(-1E3!=a.Na.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Na.g=c;c=(0,window.parseInt)(b.params.currentTime,10);m7(a.Na,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},xma=function(a,b){var c="true"==b.params.muted;
a.Na.volume=(0,window.parseInt)(b.params.volume,10);a.Na.muted=c;a.P("remotePlayerChange")},yma=function(a,b){a.F=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},zma=function(a,b){var c="true"==b.params.hasNext;
a.Na.Se="true"==b.params.hasPrevious;a.Na.hasNext=c;a.P("previousNextChange")},I7=function(a){g.lr(a.J);
a.J=g.jr((0,g.A)(a.C,a,1),864E5)},H7=function(a,b,c){c?C7("Sending: action="+b+", params="+g.Sg(c)):C7("Sending: action="+b);
a.g.sendMessage(b,c)},M7=function(a){n6.call(this,"ScreenServiceProxy");
this.Dc=a;this.l=[];this.l.push(this.Dc.$_s("screenChange",(0,g.A)(this.ZM,this)));this.l.push(this.Dc.$_s("onlineScreenChange",(0,g.A)(this.PJ,this)))},Ema=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.er("MDX_CONFIG")||b;Mla();N4();N7||(N7=new c6(b?b.loungeApiHost:void 0),T4()&&(N7.g="/api/loungedev"));O7||(O7=g.z("yt.mdx.remote.deferredProxies_")||[],g.y("yt.mdx.remote.deferredProxies_",O7,void 0));Ama();var c=P7();if(!c){var d=new A6(N7);g.y("yt.mdx.remote.screenService_",d,void 0);c=P7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);pma(a,d,function(a){a?Q7()&&i7(Q7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.gt("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.y("yt.mdx.remote.initialized_",!0,void 0),R7("Initializing: "+g.Sg(b)),S7.push(g.ct("yt-remote-cast2-availability-change",function(){g.gt("yt-remote-receiver-availability-change")})),S7.push(g.ct("yt-remote-cast2-receiver-selected",function(){T7(null);
g.gt("yt-remote-auto-connect","cast-selector-receiver")})),S7.push(g.ct("yt-remote-cast2-receiver-resumed",function(){g.gt("yt-remote-receiver-resumed","cast-selector-receiver")})),S7.push(g.ct("yt-remote-cast2-session-change",Bma)),S7.push(g.ct("yt-remote-connection-change",function(a){a?i7(Q7(),"YouTube TV"):U7()||(i7(null,null),e7())})),a=V7(),b.isAuto&&(a.id+="#dial"),g.Xs("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),R7(" -- with channel params: "+
g.Sg(a)),Cma(a),c.start(),Q7()||Dma())},Fma=function(){var a=W7();
c7()&&g.du("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},W7=function(){var a=P7().Dc.$_gos();
var b=X7();b&&Y7()&&(H4(a,b)||a.push(b));return Lla(a)},Z7=function(){var a=Gma();
!a&&c7()&&d7()&&(a={key:"cast-selector-receiver",name:d7()});return a},Gma=function(){var a=W7(),b=X7();
b||(b=U7());return g.Sa(a,function(a){return b&&B4(b,a.key)?!0:!1})},X7=function(){var a=Q7();
if(!a)return null;var b=P7().Dd();return I4(b,a)},Bma=function(a){R7("remote.onCastSessionChange_: "+E4(a));
if(a){var b=X7();b&&b.id==a.id?i7(b.id,"YouTube TV"):(b&&$7(),a8(a,1))}else Y7()&&$7()},$7=function(){g7()?$6().stopSession():X6("stopSession called before API ready.");
var a=Y7();a&&(a.disconnect(1),b8(null))},c8=function(){var a=Y7();
return!!a&&3!=a.getProxyState()},R7=function(a){j6("remote",a)},P7=function(){if(!d8){var a=g.z("yt.mdx.remote.screenService_");
d8=a?new M7(a):null}return d8},Q7=function(){return g.z("yt.mdx.remote.currentScreenId_")},e8=function(a){g.y("yt.mdx.remote.currentScreenId_",a,void 0)},f8=function(){return g.z("yt.mdx.remote.connectData_")},T7=function(a){g.y("yt.mdx.remote.connectData_",a,void 0)},Y7=function(){return g.z("yt.mdx.remote.connection_")},b8=function(a){var b=Y7();
T7(null);a||e8("");g.y("yt.mdx.remote.connection_",a,void 0);O7&&((0,g.C)(O7,function(b){b(a)}),O7.length=0);
b&&!a?g.gt("yt-remote-connection-change",!1):!b&&a&&g.gt("yt-remote-connection-change",!0)},U7=function(){var a=g.fu();
if(!a)return null;var b=P7().Dd();return I4(b,a)},a8=function(a,b){X7()&&X7();
e8(a.id);var c=new B7(N7,a,V7());c.connect(b,f8());c.subscribe("beforeDisconnect",function(a){g.gt("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Y7()&&b8(null)});
b8(c)},Dma=function(){var a=U7();
a?(R7("Resume connection to: "+E4(a)),a8(a,0)):(R4(),e7(),R7("Skipping connecting because no session screen found."))},Ama=function(){var a=V7();
if(g.mc(a)){a=M4();var b=g.du("yt-remote-session-name")||"",c=g.du("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.y("yt.mdx.remote.channelParams_",a,void 0)}},V7=function(){return g.z("yt.mdx.remote.channelParams_")||{}},Cma=function(a){a?(g.cu("yt-remote-session-app",a.app),g.cu("yt-remote-session-name",a.name)):(g.eu("yt-remote-session-app"),g.eu("yt-remote-session-name"));
g.y("yt.mdx.remote.channelParams_",a,void 0)},g8=function(a,b,c){g.F.call(this);
this.F=a;this.L=b;this.l=new g.Ps(this);g.I(this,this.l);this.l.M(b,"onCaptionsTrackListChanged",this.iJ);this.l.M(b,"captionschanged",this.dI);this.l.M(b,"captionssettingschanged",this.Vz);this.l.M(b,"videoplayerreset",this.dn);this.l.M(b,"mdxautoplaycancel",this.bC);this.T=this.l.M(b,"onVolumeChange",this.jy);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.wy,this);c.subscribe("remotePlayerChange",this.Ak,this);c.subscribe("remoteQueueChange",this.dn,this);c.subscribe("autoplayUpNext",this.Tx,
this);c.subscribe("previousNextChange",this.ty,this);c.subscribe("nowAutoplaying",this.my,this);c.subscribe("autoplayDismissed",this.Sx,this);this.suggestion=null;this.G=new g.WC(64);this.o=new g.L(this.Sz,500,this);g.I(this,this.o);this.A=new g.L(this.Tz,1E3,this);g.I(this,this.A);this.J=new b5(this.FM,0,this);g.I(this,this.J);this.B={};this.N=new g.L(this.tA,1E3,this);g.I(this,this.N);this.H=new g.Cm(this.hG,1E3,this);g.I(this,this.H);this.R=g.Aa;this.Vz();this.dn();this.Ak()},h8=function(a,b){a.F.md(b,
a.L.getVideoData().lengthSeconds)},j8=function(a){h8(a,0);
a.o.stop();i8(a,new g.WC(64))},l8=function(a,b){if(k8(a)&&!a.C){var c=null;
b&&(c={style:a.L.Bh()},g.uc(c,b));a.g.Jz(a.L.getVideoData(1).videoId,c);a.B=t7(a.g).l}},m8=function(a,b){var c=a.L.Ve();
if(c){var d=c.Ra;var e=c.listId.toString()}var f=a.L.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.pi;f=w4(f);var n=t7(c);l=l||0;var q={videoId:k,currentIndex:l};o7(n,k,l);g.t(b)&&(m7(n,b),q.currentTime=b);g.t(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.Sg(f));y7(c,"setPlaylist",q);e||w7(c,n);i8(a,new g.WC(1))},n8=function(a,b){if(b){var c=a.L.Ub("captions","tracklist",{ov:1});
c&&c.length?(a.L.fd("captions","track",b),a.C=!1):(a.L.Ei("captions"),a.C=!0)}else a.L.fd("captions","track",{})},k8=function(a){return t7(a.g).videoId==a.L.getVideoData(1).videoId},i8=function(a,b){a.A.stop();
var c=a.G;if(!g.aD(c,b)){var d=g.V(b,2);d!=g.V(a.G,2)&&g.qJ(a.L,d);a.G=b;o8(a.F,c,b)}},q8=function(a){g.R.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.YN()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.l=new g.RO(this,250);g.I(this,this.l);this.o=a;this.M(a,"presentingplayerstatechange",this.A);p8(this,g.mJ(a))},p8=function(a,b){if(3==a.o.Da()){var c={RECEIVER_NAME:a.o.Ub("remote","currentReceiver").name};
c=g.V(b,128)?g.mW("Erro em $RECEIVER_NAME",c):g.cD(b)||g.V(b,4)?g.mW("Reproduzindo em $RECEIVER_NAME",c):g.mW("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},r8=function(a,b){g.iS.call(this,"Reproduzir em",0,a,b);
this.L=a;this.F={};this.M(a,"onMdxReceiversChange",this.H);this.M(a,"presentingplayerstatechange",this.H);this.H()},s8=function(a){g.WJ.call(this,a);
this.o={key:G4(),name:"Este computador"};this.B=null;this.C=[];this.H=this.l=null;this.G=[this.o];this.A=this.o;this.F=new g.WC(64);this.J=0;if(!g.$z(g.W(this.g))){a=this.g;var b=g.Vu(a);b&&(b=b.Pm())&&(b=new r8(a,b),g.I(this,b));b=new q8(a);g.I(this,b);g.IJ(a,b.element,4)}},o8=function(a,b,c){a.F=c;
a.g.P("presentingplayerstatechange",new g.hD(c,b))},t8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)$7();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.Ve();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ub(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.pi,index:Math.max(a.g.qw(),0),currentTime:0==f?void 0:f};(d=w4(d))&&(c.locationInfo=d);d=c}else d=null;R7("Connecting to: "+g.Sg(b));"cast-selector-receiver"==b.key?(T7(d||null),g7()?$6().setLaunchParams(d||null):
X6("setLaunchParams called before ready.")):!d&&c8()&&Q7()==b.key?g.gt("yt-remote-connection-change",!0):($7(),T7(d||null),d=P7().Dd(),(d=I4(d,b.key))&&a8(d,1))}},Cla=/^https?$/i,Hma=["POST",
"PUT"];g.B(u4,g.Qf);g.h=u4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.B="";this.A=0;this.Y=b;this.U=!1;this.l=!0;this.g=this.T?m4(this.T):m4(g.NW);this.R=this.T?l4(this.T):l4(g.NW);this.g.onreadystatechange=(0,g.A)(this.Tu,this);try{h4(n4(this,"Opening Xhr")),this.Z=!0,this.g.open(b,String(a),!0),this.Z=!1}catch(f){h4(n4(this,"Error opening Xhr: "+f.message));r4(this,f);return}a=c||"";var e=this.headers.clone();
d&&zla(d,function(a,b){e.set(b,a)});
d=g.Sa(e.Bd(),Ala);c=g.w.FormData&&a instanceof g.w.FormData;!g.Wa(Hma,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.ga&&(this.g.responseType=this.ga);"withCredentials"in this.g&&this.g.withCredentials!==this.ba&&(this.g.withCredentials=this.ba);try{o4(this),0<this.C&&(this.N=Bla(this.g),h4(n4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.N)),this.N?(this.g.timeout=this.C,this.g.ontimeout=(0,g.A)(this.Uu,this)):this.F=g.Ig(this.Uu,this.C,this)),h4(n4(this,"Sending request")),this.G=!0,this.g.send(a),this.G=!1}catch(f){h4(n4(this,"Send error: "+f.message)),r4(this,f)}};
g.h.Uu=function(){"undefined"!=typeof g.qW&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,n4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(n4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),q4(this))};
g.h.V=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),q4(this,!0));u4.ya.V.call(this)};
g.h.Tu=function(){this.fa()||(this.Z||this.G||this.o?t4(this):this.oK())};
g.h.oK=function(){t4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<s4(this)?this.g.status:-1}catch(a){return-1}};
var q5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},p5={"'":"\\'"},Ima={};g.h=x4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.l.length};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Wa(this.g,a)||g.Wa(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.vha)(b,a);0<=c?(g.Za(b,c),b=!0):b=!1;return b||g.ab(this.l,a)};
g.h.wc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var Jla={oN:"atp",zP:"ska",oP:"que",PO:"mus",yP:"sus",fO:"dsp"};z4.prototype.zl=function(){var a=new z4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var S4,L4="",Z4=U4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Ula=U4("loadCastFramework")||U4("loadCastApplicationFramework"),oma=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(b5,g.F);g.h=b5.prototype;g.h.FC=function(a){this.A=arguments;this.g=!1;this.Ca?this.o=(0,g.D)()+this.Rc:this.Ca=g.Ig(this.B,this.Rc)};
g.h.stop=function(){this.Ca&&(g.w.clearTimeout(this.Ca),this.Ca=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();b5.ya.V.call(this)};
g.h.GC=function(){this.o?(this.Ca=g.Ig(this.B,this.o-(0,g.D)()),this.o=null):(this.Ca=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};c5.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
c5.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=d5.prototype;g.h.jh=null;g.h.Be=!1;g.h.dj=null;g.h.Es=null;g.h.Ri=null;g.h.ni=null;g.h.sg=null;g.h.Jg=null;g.h.Eh=null;g.h.sc=null;g.h.Uk=0;g.h.Ce=null;g.h.bo=null;g.h.tg=null;g.h.Tj=-1;g.h.wz=!0;g.h.Yg=!1;g.h.Ep=0;g.h.un=null;var k5={},i5={};g.h=d5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.PL=function(a){a=a.target;var b=this.un;b&&3==s4(a)?b.Oj():this.CA(a)};
g.h.CA=function(a){try{if(a==this.sc)a:{var b=s4(this.sc),c=this.sc.A,d=this.sc.getStatus();if(g.Wd&&!g.Ic(10)||g.Yd&&!g.Gc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Uh&&!v4(this.sc))break a;this.Yg||4!=b||7==c||(8==c||0>=d?this.g.xe(3):this.g.xe(2));u5(this);var e=this.sc.getStatus();this.Tj=e;var f=v4(this.sc);(this.Be=200==e)?(4==b&&m5(this),this.B?(o5(this,b,f),g.Uh&&this.Be&&3==b&&(this.ca.ea(this.l,"tick",this.LL),this.l.start())):l5(this,f),this.Be&&!this.Yg&&(4==b?this.g.bn(this):(this.Be=
!1,h5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.tg=3,j5(13)):(this.tg=0,j5(14)),m5(this),n5(this))}}catch(k){this.sc&&v4(this.sc)}finally{}};
g.h.LL=function(){var a=s4(this.sc),b=v4(this.sc);this.Uk<b.length&&(u5(this),o5(this,a,b),this.Be&&4!=a&&h5(this))};
g.h.jL=function(a){t5((0,g.A)(this.iL,this,a),0)};
g.h.iL=function(a){this.Yg||(u5(this),l5(this,a),h5(this))};
g.h.Fy=function(a){t5((0,g.A)(this.hL,this,a),0)};
g.h.hL=function(a){this.Yg||(m5(this),this.Be=a,this.g.bn(this),this.g.xe(4))};
g.h.cancel=function(){this.Yg=!0;m5(this)};
g.h.uL=function(){this.dj=null;var a=(0,g.D)();0<=a-this.Es?(2!=this.ni&&this.g.xe(3),m5(this),this.tg=2,j5(18),n5(this)):s5(this,this.Es-a)};g.h=y5.prototype;g.h.Cp=null;g.h.Kd=null;g.h.vn=!1;g.h.Su=null;g.h.Pl=null;g.h.gq=null;g.h.Dp=null;g.h.Xd=null;g.h.wf=-1;g.h.Sj=null;g.h.nj=null;g.h.connect=function(a){this.Dp=a;a=z5(this.g,null,this.Dp);j5(3);this.Su=(0,g.D)();var b=this.g.G;null!=b?(this.Sj=b[0],(this.nj=b[1])?(this.Xd=1,A5(this)):(this.Xd=2,C5(this))):(j4(a,"MODE","init"),this.Kd=new d5(this,void 0,void 0,void 0),this.Kd.jh=this.Cp,g5(this.Kd,a,!1,null,!0),this.Xd=0)};
g.h.cC=function(a){if(a)this.Xd=2,C5(this);else{j5(4);var b=this.g;b.Pe=b.hg.wf;W5(b,9)}a&&this.xe(2)};
g.h.Wo=function(a){return this.g.Wo(a)};
g.h.abort=function(){this.Kd&&(this.Kd.cancel(),this.Kd=null);this.wf=-1};
g.h.Ru=function(){return!1};
g.h.yy=function(a,b){this.wf=a.Tj;if(0==this.Xd)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Pe=this.wf;W5(c,2);return}this.Sj=c[0];this.nj=c[1]}else c=this.g,c.Pe=this.wf,W5(c,2);else if(2==this.Xd)if(this.vn)j5(7),this.gq=(0,g.D)();else if("11111"==b){if(j5(6),this.vn=!0,this.Pl=(0,g.D)(),c=this.Pl-this.Su,!g.Wd||g.Ic(10)||500>c)this.wf=200,this.Kd.cancel(),j5(12),B5(this.g,this,!0)}else j5(8),this.Pl=this.gq=(0,g.D)(),this.vn=!1};
g.h.bn=function(){this.wf=this.Kd.Tj;if(this.Kd.Be)0==this.Xd?this.nj?(this.Xd=1,A5(this)):(this.Xd=2,C5(this)):2==this.Xd&&((!g.Wd||g.Ic(10)?!this.vn:200>this.gq-this.Pl)?(j5(11),B5(this.g,this,!1)):(j5(12),B5(this.g,this,!0)));else{0==this.Xd?j5(9):2==this.Xd&&j5(10);var a=this.g;a.Pe=this.wf;W5(a,2)}};
g.h.Lk=function(){return this.g.Lk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.xe=function(a){this.g.xe(a)};g.h=D5.prototype;g.h.Aj=null;g.h.td=null;g.h.Rb=null;g.h.Bp=null;g.h.Tl=null;g.h.Gt=null;g.h.fm=null;g.h.wk=0;g.h.wH=0;g.h.Qc=null;g.h.ng=null;g.h.kf=null;g.h.bh=null;g.h.hg=null;g.h.Zn=null;g.h.wi=-1;g.h.Kv=-1;g.h.Pe=-1;g.h.hi=0;g.h.Yh=0;g.h.Zg=8;var X5=new g.Qf;g.B(E5,g.nf);g.B(F5,g.nf);g.B(G5,g.nf);g.h=D5.prototype;g.h.connect=function(a,b,c,d,e){j5(0);this.Bp=b;this.Aj=c||{};d&&g.t(e)&&(this.Aj.OSID=d,this.Aj.OAID=e);this.C?(t5((0,g.A)(this.Zt,this,a),100),M5(this)):this.Zt(a)};
g.h.Zt=function(a){this.hg=new y5(this);this.hg.Cp=null;this.hg.l=this.B;this.hg.connect(a)};
g.h.Ru=function(){return 0==this.g};
g.h.Dy=function(a){this.ng=null;R5(this,a)};
g.h.Cy=function(){this.kf=null;this.Rb=new d5(this,this.o,"rpc",this.F);this.Rb.jh=null;this.Rb.Ep=0;var a=this.Gt.clone();g.Ro(a,"RID","rpc");g.Ro(a,"SID",this.o);g.Ro(a,"CI",this.Zn?"0":"1");g.Ro(a,"AID",this.wi);I5(this,a);if(!g.Wd||g.Ic(10))g.Ro(a,"TYPE","xmlhttp"),g5(this.Rb,a,!0,this.fm,!1);else{g.Ro(a,"TYPE","html");var b=this.Rb,c=!!this.fm;b.ni=3;b.sg=i4(a.clone());r5(b,c)}};
g.h.yy=function(a,b){if(0!=this.g&&(this.Rb==a||this.td==a))if(this.Pe=a.Tj,this.td==a&&3==this.g)if(7<this.Zg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Da(c)&&3==c.length)if(0==c[0])a:{if(!this.kf){if(this.Rb)if(this.Rb.Ri+3E3<this.td.Ri)N5(this),this.Rb.cancel(),this.Rb=null;else break a;U5(this);j5(19)}}else this.Kv=c[1],0<this.Kv-this.wi&&37500>c[2]&&this.Zn&&0==this.Yh&&!this.bh&&(this.bh=t5((0,g.A)(this.ZH,this),6E3));else W5(this,11)}else b!=Ima.ON.g&&W5(this,11);else if(this.Rb==a&&
N5(this),!g.zb(b)){c=this.B.parse(b);g.Da(c);for(var d=0;d<c.length;d++){var e=c[d];this.wi=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.fm=e[2],e=e[3],null!=e?this.Zg=e:this.Zg=6,this.g=3,this.Qc&&this.Qc.Pt(),this.Gt=z5(this,this.Lk()?this.fm:null,this.Bp),S5(this)):"stop"==e[0]&&W5(this,7):3==this.g&&("stop"==e[0]?W5(this,7):"noop"!=e[0]&&this.Qc&&this.Qc.Ot(e),this.Yh=0)}}};
g.h.ZH=function(){null!=this.bh&&(this.bh=null,this.Rb.cancel(),this.Rb=null,U5(this),j5(20))};
g.h.bn=function(a){if(this.Rb==a){N5(this);this.Rb=null;var b=2}else if(this.td==a)this.td=null,b=1;else return;this.Pe=a.Tj;if(0!=this.g)if(a.Be)1==b?(b=(0,g.D)()-a.Ri,X5.dispatchEvent(new F5(X5,a.Eh?a.Eh.length:0,b,this.hi)),L5(this),this.A.length=0):S5(this);else{var c=a.tg,d;if(!(d=3==c||7==c||0==c&&0<this.Pe)){if(d=1==b)this.td||this.ng||1==this.g||2<=this.hi?d=!1:(this.ng=t5((0,g.A)(this.Dy,this,a),T5(this,this.hi)),this.hi++,d=!0);d=!(d||2==b&&U5(this))}if(d)switch(c){case 1:W5(this,5);break;
case 4:W5(this,10);break;case 3:W5(this,6);break;case 7:W5(this,12);break;default:W5(this,2)}}};
g.h.qC=function(a){if(!g.Wa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.sM=function(a){a?j5(2):(j5(1),V5(this,8))};
g.h.Wo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new u4;a.ba=!1;return a};
g.h.isActive=function(){return!!this.Qc&&this.Qc.isActive(this)};
g.h.xe=function(a){X5.dispatchEvent(new G5(X5,a))};
g.h.Lk=function(){return!(!g.Wd||g.Ic(10))};
g.h=Y5.prototype;g.h.Pt=function(){};
g.h.Ot=function(){};
g.h.Nt=function(){};
g.h.Lo=function(){};
g.h.Bu=function(){return{}};
g.h.isActive=function(){return!0};g.B(Z5,g.F);g.h=Z5.prototype;g.h.cL=function(){this.Rc=Math.min(3E5,2*this.Rc);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.Rc+15E3*Math.random();g.Vp(this.g,a);this.l=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Rc=5E3};g.B($5,Y5);g.h=$5.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Hc=function(a){return this.o.Hc(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.lf(this.o),a6(this),g.lf(this.l),this.l=null)};
g.h.fa=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new D5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.g;e&&(e.Qc=null);d.Qc=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.wi):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.uc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):b6(this)&&O5(this.g,c)};
g.h.Pt=function(){this.l.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)O5(this.g,a[b])}this.P("handlerOpened")};
g.h.Nt=function(a){var b=2==a&&401==this.g.Pe;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.Lo=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Bu=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.uc(a,this.B);return a};
g.h.Ot=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),K5(this.g)):this.P("handlerMessage",new Zla(a[0],a[1]))};
g.h.VM=function(){this.l.isActive();var a=this.g,b=0;a.Rb&&b++;a.td&&b++;0!=b||this.connect(this.B,this.A)};c6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
c6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
c6.prototype.B=function(a){a(Error("request timed out"))};var ema=(0,g.D)(),h6=null,l6=Array(50),k6=-1,m6=!1;g.B(n6,g.O);n6.prototype.Dd=function(){return this.g};
n6.prototype.contains=function(a){return!!H4(this.g,a)};
n6.prototype.get=function(a){return a?I4(this.g,a):null};
n6.prototype.info=function(a){j6(this.F,a)};g.B(p6,g.O);var u8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=p6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ca)&&this.GA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ca)||(g.lr(this.Ca),this.Ca=window.NaN)};
g.h.V=function(){this.stop();p6.ya.V.call(this)};
g.h.GA=function(){this.Ca=window.NaN;this.g=g.Br(d6(this.C,"/pairing/get_screen"),{method:"POST",ib:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.A)(this.XM,this),onError:(0,g.A)(this.WM,this),hd:(0,g.A)(this.YM,this)})};
g.h.XM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new A4(c))};
g.h.WM=function(a){this.g=null;a.status&&404==a.status?this.l>=u8.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=u8[this.l],this.Ca=g.jr((0,g.A)(this.GA,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.YM=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.B(r6,n6);g.h=r6.prototype;g.h.start=function(){q6(this)&&this.P("screenChange");!g.du("yt-remote-lounge-token-expiration")&&s6(this);g.lr(this.l);this.l=g.jr((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){q6(this);o6(this,a);t6(this,!1);this.P("screenChange");b(a);a.token||s6(this)};
g.h.remove=function(a,b){var c=q6(this);gma(this,a)&&(t6(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Un=function(a,b,c,d){var e=q6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,t6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.V=function(){g.lr(this.l);r6.ya.V.call(this)};
g.h.RC=function(a){q6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}t6(this,!b);b&&j6(this.F,"Missed "+b+" lounge tokens.")};
g.h.QC=function(a){j6(this.F,"Requesting lounge tokens failed: "+a)};g.B(v6,g.O);g.h=v6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.du("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.D)()-144E5<a?0:a)?y6(this):(this.A=(0,g.D)()+3E5,g.cu("yt-remote-fast-check-period",this.A),this.Pr())};
g.h.isEmpty=function(){return g.mc(this.g)};
g.h.update=function(){u6("Updating availability on schedule.");var a=this.C(),b=g.ac(this.g,function(b,d){return b&&!!I4(a,d)},this);
x6(this,b)};
g.h.V=function(){g.lr(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);v6.ya.V.call(this)};
g.h.Pr=function(){g.lr(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=z6(this);if(g.dc(a)){var b=d6(this.B,"/pairing/get_screen_availability");this.l=e6(this.B,b,{lounge_token:g.gc(a).join(",")},(0,g.A)(this.JK,this,a),(0,g.A)(this.IK,this))}else x6(this,{}),y6(this)};
g.h.JK=function(a,b){this.l=null;var c=g.gc(z6(this));if(g.sb(c,g.gc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;x6(this,d);y6(this)}else this.Eb("Changing Screen set during request."),this.Pr()};
g.h.IK=function(a){this.Eb("Screen availability failed: "+a);this.l=null;y6(this)};
g.h.Eb=function(a){j6("OnlineScreenService",a)};g.B(A6,n6);g.h=A6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Un=function(a,b,c,d){this.o.contains(a)?this.o.Un(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j6(this.F,a),d(Error(a)))};
g.h.Dd=function(a){return a?this.g:g.db(this.g,(0,g.ke)(this.A,function(a){return!this.contains(a)},this))};
g.h.HA=function(){return(0,g.ke)(this.Dd(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.IA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.lf(f);d(B6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.lf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.aN=function(a,b,c,d){g.Br(d6(this.C,"/pairing/get_screen"),{method:"POST",ib:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new A4(d.screen||{});if(!e.name||D6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);D6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(B6(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
hd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.lf(this.o);g.lf(this.l);A6.ya.V.call(this)};
g.h.cD=function(){E6(this);this.P("screenChange");this.l.update()};
A6.prototype.dispose=A6.prototype.dispose;g.B(G6,g.O);g.h=G6.prototype;g.h.cn=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.Id=function(a){this.fa()||(a&&H6(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){j6(this.R,a)};
g.h.KA=function(){return null};
g.h.Ur=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){H6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Ur("");G6.ya.V.call(this)};g.B(J6,G6);g.h=J6.prototype;g.h.Tr=function(a){if(this.g){if(this.g==a)return;H6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);lma(this)};
g.h.xi=function(a){this.info("launchWithParams no-op for Cast: "+g.Sg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.Id()},this),(0,g.A)(function(){this.Id(Error("Failed to stop receiver app."))},this)):this.Id(Error("Stopping cast device witout session."))};
g.h.Ur=g.Aa;g.h.V=function(){this.info("disposeInternal");g.lr(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;J6.ya.V.call(this)};
g.h.FL=function(a,b){if(!this.fa())if(b){var c=g.fq(b);if(g.Ga(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Sg(c));switch(d){case "mdxSessionStatus":I6(this,c.screenId);break;default:H6(this,"Unknown youtube message: "+d)}}else H6(this,"Unable to parse message.")}else H6(this,"No data in message.")};
g.h.Ju=function(a,b,c,d){C6(this.H,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(H6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.jr((0,g.A)(this.Ju,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.KA=function(){return this.g};
g.h.bN=function(a){this.fa()||a||(H6(this,"Cast session died."),this.Id())};g.B(K6,G6);g.h=K6.prototype;g.h.Tr=function(a){this.A=a;this.A.addUpdateListener(this.N)};
g.h.xi=function(a){this.B=a;this.F()};
g.h.stop=function(){this.g();this.g=g.Aa;g.lr(this.C);this.A?this.A.stop((0,g.A)(this.Id,this,null),(0,g.A)(this.Id,this,"Failed to stop DIAL device.")):this.Id()};
g.h.V=function(){this.g();this.g=g.Aa;g.lr(this.C);this.A&&this.A.removeUpdateListener(this.N);this.A=null;K6.ya.V.call(this)};
g.h.eN=function(a){this.fa()||a||(H6(this,"DIAL session died."),this.g(),this.g=g.Aa,this.Id())};
g.h.Sp=function(a){this.J=G4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,M6(this));a(b);L6(this)}else this.F=(0,g.A)(function(){g.lr(this.C);this.F=g.Aa;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,M6(this));a(b);L6(this)},this),this.C=g.jr((0,g.A)(function(){this.F()},this),100)};
g.h.yD=function(a,b,c){C6(this.H,this.G.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.cn(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Sp(b,c)},this),(0,g.A)(function(a){H6(this,"Failed to get DIAL screen: "+a);
this.Sp(b,c)},this))};g.B(N6,G6);N6.prototype.stop=function(){this.Id()};
N6.prototype.Tr=g.Aa;N6.prototype.xi=function(){g.lr(this.g);this.g=window.NaN;var a=I4(this.H.Dd(),this.l.label);a?this.cn(a):this.Id(Error("No such screen"))};
N6.prototype.V=function(){g.lr(this.g);this.g=window.NaN;N6.ya.V.call(this)};g.B(O6,g.O);g.h=O6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.Ay,this),(0,g.A)(this.tK,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.AI,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.fa()||(window.chrome.cast.addReceiverActionListener(this.A),bma(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.JA,this)),this.o=T6(this),window.chrome.cast.setCustomReceivers(this.o,g.Aa,(0,g.A)(function(a){this.Eb("Failed to set initial custom receivers: "+g.Sg(a))},this)),this.P("yt-remote-cast2-availability-change",R6(this)),b(!0))},this),(0,g.A)(function(a){this.Eb("Failed to initialize API: "+g.Sg(a));
b(!1)},this))};
g.h.iM=function(a,b){Q6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)Q6("Unsetting old screen status: "+this.g.l.friendlyName),S6(this,null)}if(a&&b){if(!this.g){c=I4(this.l.Dd(),a);if(!c){Q6("setConnectedScreenStatus: Unknown screen.");return}var d=P6(this,c);d||(Q6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.Aa,(0,g.A)(function(a){this.Eb("Failed to set initial custom receivers: "+g.Sg(a))},this)));
Q6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);S6(this,new N6(this.l,d),!0)}this.g.Ur(b)}else Q6("setConnectedScreenStatus: no screen.")};
g.h.jM=function(a){this.fa()?this.Eb("Setting connection data on disposed cast v2"):this.g?this.g.xi(a):this.Eb("Setting connection data without a session")};
g.h.dN=function(){this.fa()?this.Eb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),S6(this,null)):Q6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.Ay,this),(0,g.A)(this.OK,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.JA,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.ab(g.z("yt.mdx.remote.debug.handlers_")||[],f6);g.lf(this.g);O6.ya.V.call(this)};
g.h.Eb=function(a){j6("Controller",a)};
g.h.By=function(a,b){this.g==a&&(b||S6(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.pK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),Q6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)Q6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{Q6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:S6(this,
new N6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:S6(this,new K6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:S6(this,new J6(this.l,a));break;default:this.Eb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Eb("Stopping receiver w/o session: "+a.friendlyName)}else this.Eb("onReceiverAction_ called without receiver.")};
g.h.AI=function(a){if(this.fa())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Eb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Eb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return Q6("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Eb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);S6(this,new K6(this.l,b,this.C))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.yD,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Sp,b))};
g.h.Ay=function(a){if(!this.fa()){Q6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)Q6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),S6(this,new J6(this.l,b),!0);else{this.Eb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=I4(this.l.Dd(),c.label);
d&&B4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(Q6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.lf(this.g),this.g=new J6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.By,this,this.g)),this.g.xi(null));this.g.Tr(a)}}};
g.h.cN=function(){return this.g?this.g.KA():null};
g.h.OK=function(a){this.fa()||(this.Eb("Failed to estabilish a session: "+g.Sg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&S6(this,null))};
g.h.tK=function(a){Q6("Receiver availability updated: "+a);if(!this.fa()){var b=R6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;R6(this)!=b&&this.P("yt-remote-cast2-availability-change",R6(this))}};
g.h.JA=function(){this.fa()||(this.o=T6(this),Q6("Updating custom receivers: "+g.Sg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.Aa,(0,g.A)(function(){this.Eb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",R6(this)))};
O6.prototype.setLaunchParams=O6.prototype.jM;O6.prototype.setConnectedScreenStatus=O6.prototype.iM;O6.prototype.stopSession=O6.prototype.dN;O6.prototype.getCastSession=O6.prototype.cN;O6.prototype.requestSession=O6.prototype.requestSession;O6.prototype.init=O6.prototype.init;O6.prototype.dispose=O6.prototype.dispose;var b7=[];j7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";k7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Se=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
j7.prototype.isAdPlaying=function(){return 1081==this.g};
j7.prototype.clone=function(){return new j7(p7(this))};g.B(s7,g.O);g.h=s7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.Aa,A7(this,"play")):y7(this,"play"),x7(this,1,n7(t7(this))),this.P("remotePlayerChange")):v7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.Aa,A7(this,"pause")):y7(this,"pause"),x7(this,2,n7(t7(this))),this.P("remotePlayerChange")):v7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.l){var b=t7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.g||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.Aa,A7(this,"seekTo",{newTime:a}))}else y7(this,"seekTo",{newTime:a});x7(this,3,a);this.P("remotePlayerChange")}else v7(this,g.Ma(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.Aa,A7(this,"stopVideo")):y7(this,"stopVideo");var a=t7(this);a.index=-1;a.videoId="";k7(a);w7(this,a);this.P("remotePlayerChange")}else v7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=t7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){j6("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.Eb("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){j6("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.Eb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);y7(this,"setVolume",e)}c.muted=b;c.volume=a;w7(this,c)}else v7(this,g.Ma(this.setVolume,a,b))};
g.h.Jz=function(a,b){if(1==this.g){var c=t7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Sg(b.style),g.uc(d,c.l));y7(this,"setSubtitlesTrack",d);w7(this,c)}else v7(this,g.Ma(this.Jz,a,b))};
g.h.Fs=function(a,b){if(1==this.g){y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.fb.id});var c=t7(this);c.audioTrackId=b.fb.id;w7(this,c)}else v7(this,g.Ma(this.Fs,a,b))};
g.h.FA=function(a,b){if(1==this.g){if(a&&b){var c=t7(this);o7(c,a,b);w7(this,c)}y7(this,"previous")}else v7(this,g.Ma(this.FA,a,b))};
g.h.EA=function(a,b){if(1==this.g){if(a&&b){var c=t7(this);o7(c,a,b);w7(this,c)}y7(this,"next")}else v7(this,g.Ma(this.EA,a,b))};
g.h.ou=function(){1==this.g?y7(this,"dismissAutoplay"):v7(this,this.ou)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}s7.ya.dispose.call(this)};
g.h.V=function(){u7(this);this.A=null;this.B.clear();r7(this,null);s7.ya.V.call(this)};
g.h.Gs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0==b.g.length&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.lK=function(a,b){this.P(a,b)};
g.h.fI=function(a){if(!a)this.yk(null),r7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=t7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,w7(this,b)}};
g.h.yk=function(a){j6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.G);if(this.l=a)this.l.addUpdateListener(this.G),z7(this),this.P("remotePlayerChange")};
g.h.eI=function(a){a?(z7(this),this.P("remotePlayerChange")):this.yk(null)};
g.h.rI=function(){var a=f7();a&&r7(this,a)};
g.h.Eb=function(a){j6("CP",a)};g.B(B7,g.O);g.h=B7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Na.listId=c);this.Na.videoId=d;this.Na.index=k||0;this.Na.state=3;m7(this.Na,m);this.A="UNSUPPORTED";C7("Connecting with setPlaylist and params: "+g.Sg(l));this.g.connect({method:"setPlaylist",params:g.Sg(l)},
a,O4())}else C7("Connecting without params"),this.g.connect({},a,O4());sma(this)};
g.h.dispose=function(){this.fa()||(this.P("beforeDispose"),D7(this,3));B7.ya.dispose.call(this)};
g.h.V=function(){E7(this);G7(this);F7(this);g.lr(this.H);this.H=window.NaN;g.lr(this.J);this.J=window.NaN;this.o=null;g.Ds(this.U);this.U.length=0;this.g.dispose();B7.ya.V.call(this);this.A=this.F=this.l=this.Na=this.g=null};
g.h.KC=function(){this.C(2)};
g.h.jI=function(){C7("Channel opened");this.T&&(this.T=!1,F7(this),this.R=g.jr((0,g.A)(function(){C7("Timing out waiting for a screen.");this.C(1)},this),15E3));
Pla($la(this.g),this.Z)};
g.h.gI=function(){C7("Channel closed");(0,window.isNaN)(this.B)?R4(!0):R4();this.dispose()};
g.h.hI=function(a){R4();(0,window.isNaN)(this.G())?(C7("Channel error: "+a+" without reconnection"),this.dispose()):(this.T=!0,C7("Channel error: "+a+" with reconnection in "+this.G()+" ms"),D7(this,2))};
g.h.iI=function(a){a.params?C7("Received: action="+a.action+", params="+g.Sg(a.params)):C7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.fq(a.params.devices);this.l=(0,g.E)(a,function(a){return new z4(a)});
a=!!g.Sa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
J7(this,a);break;case "loungeScreenDisconnected":g.bb(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
J7(this,!1);break;case "remoteConnected":var b=new z4(g.fq(a.params.device));g.Sa(this.l,function(a){return b?a.id==b.id:!1})||g.Ya(this.l,b);
break;case "remoteDisconnected":b=new z4(g.fq(a.params.device));g.bb(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":K7(this,a);break;case "nowPlaying":vma(this,a);break;case "onStateChange":L7(this,a);break;case "onAdStateChange":wma(this,a);break;case "onVolumeChanged":xma(this,a);break;case "onSubtitlesTrackChanged":uma(this,a);break;case "nowAutoplaying":yma(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.P("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":zma(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:C7("Unrecognized action: "+a.action)}};
g.h.YL=function(){if(this.o){var a=this.o;this.o=null;this.Na.videoId!=a&&H7(this,"getNowPlaying")}};
B7.prototype.subscribe=B7.prototype.subscribe;B7.prototype.unsubscribeByKey=B7.prototype.Hc;B7.prototype.ia=function(){var a=3;this.fa()||(a=0,(0,window.isNaN)(this.G())?b6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
B7.prototype.getProxyState=B7.prototype.ia;B7.prototype.C=function(a){C7("Disconnecting with "+a);E7(this);this.P("beforeDisconnect",a);1==a&&R4();a6(this.g,a);this.dispose()};
B7.prototype.disconnect=B7.prototype.C;B7.prototype.da=function(){var a=this.Na;this.o&&(a=this.Na.clone(),o7(a,this.o,a.index));return p7(a)};
B7.prototype.getPlayerContextData=B7.prototype.da;
B7.prototype.pa=function(a){var b=new j7(a);b.videoId&&b.videoId!=this.Na.videoId&&(this.o=b.videoId,g.lr(this.H),this.H=g.jr((0,g.A)(this.YL,this),5E3));var c=[];this.Na.listId==b.listId&&this.Na.videoId==b.videoId&&this.Na.index==b.index||c.push("remoteQueueChange");this.Na.g==b.g&&this.Na.volume==b.volume&&this.Na.muted==b.muted&&n7(this.Na)==n7(b)&&g.Sg(this.Na.l)==g.Sg(b.l)||c.push("remotePlayerChange");this.Na.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
B7.prototype.setPlayerContextData=B7.prototype.pa;B7.prototype.ba=function(){var a=this.g.C.id,b=g.Sa(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
B7.prototype.getOtherConnectedRemoteId=B7.prototype.ba;B7.prototype.G=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.D)():window.NaN};
B7.prototype.getReconnectTimeout=B7.prototype.G;B7.prototype.Y=function(){return this.A||"UNSUPPORTED"};
B7.prototype.getAutoplayMode=B7.prototype.Y;B7.prototype.ga=function(){return this.F||""};
B7.prototype.getAutoplayVideoId=B7.prototype.ga;B7.prototype.wa=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.l;g.Wp(a.g);a.start()}};
B7.prototype.reconnect=B7.prototype.wa;B7.prototype.na=function(a,b){H7(this,a,b);I7(this)};
B7.prototype.sendMessage=B7.prototype.na;g.B(M7,n6);g.h=M7.prototype;g.h.Dd=function(a){return this.Dc.$_gs(a)};
g.h.contains=function(a){return!!this.Dc.$_c(a)};
g.h.get=function(a){return this.Dc.$_g(a)};
g.h.start=function(){this.Dc.$_st()};
g.h.add=function(a,b,c){this.Dc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Dc.$_r(a,b,c)};
g.h.Un=function(a,b,c,d){this.Dc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.Dc.$_ubk(this.l[a]);this.l.length=0;this.Dc=null;M7.ya.V.call(this)};
g.h.ZM=function(){this.P("screenChange")};
g.h.PJ=function(){this.P("onlineScreenChange")};
A6.prototype.$_st=A6.prototype.start;A6.prototype.$_gspc=A6.prototype.aN;A6.prototype.$_gsppc=A6.prototype.IA;A6.prototype.$_c=A6.prototype.contains;A6.prototype.$_g=A6.prototype.get;A6.prototype.$_a=A6.prototype.add;A6.prototype.$_un=A6.prototype.Un;A6.prototype.$_r=A6.prototype.remove;A6.prototype.$_gs=A6.prototype.Dd;A6.prototype.$_gos=A6.prototype.HA;A6.prototype.$_s=A6.prototype.subscribe;A6.prototype.$_ubk=A6.prototype.Hc;var N7=null,O7=null,d8=null,S7=[];g.r(g8,g.F);g.h=g8.prototype;
g.h.V=function(){g.F.prototype.V.call(this);this.o.stop();this.A.stop();this.J.stop();this.R();this.g.unsubscribe("proxyStateChange",this.wy,this);this.g.unsubscribe("remotePlayerChange",this.Ak,this);this.g.unsubscribe("remoteQueueChange",this.dn,this);this.g.unsubscribe("autoplayUpNext",this.Tx,this);this.g.unsubscribe("previousNextChange",this.ty,this);this.g.unsubscribe("nowAutoplaying",this.my,this);this.g.unsubscribe("autoplayDismissed",this.Sx,this);this.g=this.F=null};
g.h.Nw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(k8(this)){if(!t7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==t7(this.g).g?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Oj(c[0],c[1]);break;case "control_subtitles_set_track":l8(this,c[0]);break;case "control_set_audio_track":c=c[0],k8(this)&&this.g.Fs(this.L.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.L.getCurrentTime();m8(this,0==c?void 0:c);break;case "control_seek":m8(this,c[0]);break;case "control_subtitles_set_track":l8(this,c[0]);break;case "control_set_audio_track":c=c[0],k8(this)&&this.g.Fs(this.L.getVideoData(1).videoId,c)}};
g.h.dI=function(a){this.J.FC(a)};
g.h.FM=function(a){this.Nw("control_subtitles_set_track",g.mc(a)?null:a)};
g.h.Vz=function(){var a=this.L.Ub("captions","track");g.mc(a)||l8(this,a)};
g.h.jy=function(a){if(k8(this)){this.g.unsubscribe("remotePlayerChange",this.Ak,this);var b=Math.round(a.volume);a=!!a.muted;var c=t7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.N.start();this.g.subscribe("remotePlayerChange",this.Ak,this)}};
g.h.iJ=function(){g.mc(this.B)||n8(this,this.B);this.C=!1};
g.h.wy=function(a,b){this.A.stop();2==b&&this.Tz()};
g.h.Ak=function(){if(k8(this)){this.o.stop();var a=t7(this.g);switch(a.g){case 1081:case 1:i8(this,new g.WC(8));this.Sz();break;case 1085:case 3:i8(this,new g.WC(9));break;case 1083:case 0:i8(this,new g.WC(2));this.H.stop();h8(this,this.L.getVideoData().lengthSeconds);break;case 1084:i8(this,new g.WC(4));break;case 2:i8(this,new g.WC(4));h8(this,n7(a));break;case -1:i8(this,new g.WC(64));break;case -1E3:i8(this,new g.WC(128,{errorCode:"mdx.remoteerror",message:"Este v\u00eddeo n\u00e3o est\u00e1 dispon\u00edvel para reprodu\u00e7\u00e3o remota."}))}a=
t7(this.g).l;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,n8(this,a));a=t7(this.g);-1==a.volume||Math.round(this.L.Hb())==a.volume&&this.L.isMuted()==a.muted||this.N.isActive()||this.tA()}else j8(this)};
g.h.ty=function(){this.L.P("mdxpreviousnextchange")};
g.h.dn=function(){k8(this)||j8(this)};
g.h.bC=function(){this.g.ou()};
g.h.Tx=function(a){a&&(a=g.Br("/watch_queue_ajax",{method:"GET",zc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.nL,this)}))&&(this.R=(0,g.A)(a.abort,a))};
g.h.nL=function(a,b){var c=new g.JB(g.W(this.L),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.L.P("mdxautoplayupnext",c)};
g.h.my=function(a){(0,window.isNaN)(a)||this.L.P("mdxnowautoplaying",a)};
g.h.Sx=function(){this.L.P("mdxautoplaycanceled")};
g.h.hG=function(a,b){-1==t7(this.g).g?m8(this,a):b&&this.g.seekTo(a)};
g.h.tA=function(){if(k8(this)){var a=t7(this.g);this.l.Ka(this.T);a.muted?this.L.mute():this.L.We();this.L.setVolume(a.volume);this.T=this.l.M(this.L,"onVolumeChange",this.jy)}};
g.h.Sz=function(){this.o.stop();if(!this.g.fa()){var a=t7(this.g);1==a.g&&i8(this,new g.WC(8));h8(this,n7(a));this.o.start()}};
g.h.Tz=function(){this.A.stop();this.o.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};g.r(q8,g.R);q8.prototype.A=function(a){p8(this,a.state)};g.r(r8,g.iS);r8.prototype.H=function(){var a=this.L.Ub("remote","receivers");a&&1<a.length&&!this.L.Ub("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.jS(this,(0,g.E)(a,this.A)),a=this.L.Ub("remote","currentReceiver"),this.we(this.A(a)),this.enable(!0)):this.enable(!1)};
r8.prototype.A=function(a){return a.key};
r8.prototype.ue=function(a){return"cast-selector-receiver"==a?"Elenco...":this.F[a].name};
r8.prototype.Sc=function(a){g.iS.prototype.Sc.call(this,a);this.L.fd("remote","currentReceiver",this.F[a]);this.o.ob()};g.r(s8,g.WJ);g.h=s8.prototype;g.h.create=function(){Ema(g.Nz(g.W(this.g)));this.C.push(g.ct("yt-remote-before-disconnect",this.aI,this));this.C.push(g.ct("yt-remote-connection-change",this.uK,this));this.C.push(g.ct("yt-remote-receiver-availability-change",this.uy,this));this.C.push(g.ct("yt-remote-auto-connect",this.sK,this));this.C.push(g.ct("yt-remote-receiver-resumed",this.rK,this));this.uy()};
g.h.load=function(){this.g.Hq();g.WJ.prototype.load.call(this);this.B=new g8(this,this.g,this.l);var a=(a=f8())?a.currentTime:0;var b=c8()?new s7(Y7(),void 0):null;0==a&&b&&(a=n7(t7(b)));0!=a&&this.md(a);o8(this,this.F,this.F);g.DV(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.mf(this.B,this.l);this.l=this.B=null;g.WJ.prototype.unload.call(this);g.DV(this.g.app,5)};
g.h.V=function(){g.dt(this.C);g.WJ.prototype.V.call(this)};
g.h.Ze=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Nw.apply(this.B,[a].concat(g.qa(c)))};
g.h.CC=function(){return this.loaded?this.B.suggestion:null};
g.h.Se=function(){return this.l?t7(this.l).Se:!1};
g.h.hasNext=function(){return this.l?t7(this.l).hasNext:!1};
g.h.md=function(a,b){this.J=a||0;this.g.P("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.XF=function(){var a=t7(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.Fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.C?a.H+l7(a):a.H,ingestionTime:a.C?a.A+l7(a):a.A,isPeggedToLive:1>=(a.C?a.o+l7(a):a.o)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.C?a.o+l7(a):a.o,seekableStart:0<a.B?a.B+l7(a):a.B}};
g.h.YF=function(){this.l&&this.l.EA()};
g.h.ZF=function(){this.l&&this.l.FA()};
g.h.aI=function(a){1==a&&(this.H=this.l?t7(this.l):null)};
g.h.uK=function(){var a=c8()?new s7(Y7(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.H=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.lf(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.H)&&a.videoId==this.g.getVideoData().videoId&&this.g.pw(a.videoId,n7(a)));this.g.P("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.uy=function(){this.G=[this.o].concat(Fma());var a=Z7()||this.o;t8(this,a);this.g.ma("onMdxReceiversChange")};
g.h.sK=function(){var a=Z7();t8(this,a)};
g.h.rK=function(){this.A=Z7()};
g.h.WF=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?h7():t8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&h7(),!0):!1}};
g.h.aG=function(){y7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.dc=function(){return!1};g.uQ.remote=s8;})(_yt_player);
